#!/usr/bin/env python3
"""Bake tools/collision-editor/collision_data.json into scripts/das/data/collision_library_data.das."""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[3]
COLLISION_JSON = PROJECT / "tools" / "collision-editor" / "collision_data.json"
OUT_DAS = PROJECT / "scripts" / "das" / "data" / "collision_library_data.das"
MANIFEST = PROJECT / "scripts" / "python" / "data" / "collision_library_manifest.json"


def _f(v: float) -> str:
    if abs(v - round(v)) < 1e-6:
        return f"{int(round(v))}.0"
    return f"{v:.6f}".rstrip("0").rstrip(".")


def _float4(values: list[float]) -> str:
    return f"float4({_f(values[0])}, {_f(values[1])}, {_f(values[2])}, {_f(values[3])})"


def _float2(values: list[float]) -> str:
    return f"float2({_f(values[0])}, {_f(values[1])})"


def collect_assets(raw: dict) -> list[tuple[str, dict]]:
    assets: list[tuple[str, dict]] = []
    for tex_path, entry in raw.items():
        if not isinstance(entry, dict):
            continue
        segments = entry.get("segments") or []
        if not segments:
            continue
        assets.append((tex_path, entry))
    assets.sort(key=lambda x: x[0])
    return assets


def emit_das(assets: list[tuple[str, dict]], baked_at: str) -> str:
    paths: list[str] = []
    crops: list[str] = []
    feet_px: list[str] = []
    width_mul: list[str] = []
    low_flags: list[str] = []
    seg_offsets: list[int] = []
    all_segments: list[str] = []

    offset = 0
    for tex_path, entry in assets:
        crop = entry.get("crop") or [0, 0, 0, 0]
        feet = entry.get("feetPx") or [0, 0]
        world_w = float(entry.get("worldWidth") or 1.5)
        low = bool(entry.get("low"))
        segments = entry.get("segments") or []

        paths.append(f'        "{tex_path}"')
        crops.append(f"        {_float4([float(x) for x in crop])}")
        feet_px.append(f"        {_float2([float(x) for x in feet])}")
        width_mul.append(f"        {_f(world_w)}")
        low_flags.append("        true" if low else "        false")
        seg_offsets.append(offset)
        for seg in segments:
            if len(seg) != 4:
                continue
            all_segments.append(
                f"        {_float4([float(seg[0]), float(seg[1]), float(seg[2]), float(seg[3])])}"
            )
            offset += 1
    seg_offsets.append(offset)

    lines = [
        "// AUTO-GENERATED by scripts/python/assets/bake_collision_library.py — do not edit.",
        f"// Source: tools/collision-editor/collision_data.json",
        f"// Baked: {baked_at}",
        "require engine.core",
        "",
        "module collision_library_data public",
        "",
        "let public {",
        f'    COLLISION_LIBRARY_BAKED_AT = "{baked_at}"',
        f"    COLLISION_ASSET_COUNT = {len(assets)}",
        f"    COLLISION_SEGMENT_COUNT = {offset}",
        "    COLLISION_TEX_PATHS <- [",
        ",\n".join(paths) if paths else "",
        "    ]",
        "    COLLISION_CROPS <- [",
        ",\n".join(crops) if crops else "",
        "    ]",
        "    COLLISION_FEET_PX <- [",
        ",\n".join(feet_px) if feet_px else "",
        "    ]",
        "    COLLISION_WORLD_WIDTH_MUL <- [",
        ",\n".join(width_mul) if width_mul else "",
        "    ]",
        "    COLLISION_LOW <- [",
        ",\n".join(low_flags) if low_flags else "",
        "    ]",
        "    COLLISION_SEGMENT_OFFSETS <- [",
        ",\n".join(f"        {o}" for o in seg_offsets),
        "    ]",
        "    COLLISION_SEGMENTS <- [",
        ",\n".join(all_segments) if all_segments else "",
        "    ]",
        "}",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    if not COLLISION_JSON.is_file():
        print(f"missing {COLLISION_JSON}", file=sys.stderr)
        return 1

    raw = json.loads(COLLISION_JSON.read_text(encoding="utf-8"))
    assets = collect_assets(raw)
    baked_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    OUT_DAS.parent.mkdir(parents=True, exist_ok=True)
    OUT_DAS.write_text(emit_das(assets, baked_at), encoding="utf-8", newline="\n")

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        json.dumps(
            {
                "baked_at": baked_at,
                "asset_count": len(assets),
                "segment_count": sum(len(e.get("segments") or []) for _, e in assets),
                "source": str(COLLISION_JSON.relative_to(PROJECT)).replace("\\", "/"),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"wrote {OUT_DAS.relative_to(PROJECT)} ({len(assets)} assets)")
    print(f"wrote {MANIFEST.relative_to(PROJECT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
