"""Grid and gameplay constants mirrored from core/constants_*.das (Python bake tooling)."""

GRID_WIDTH = GRID_HEIGHT = 96
MAP_WIDTH = MAP_HEIGHT = 80
GRID_MIN_X = GRID_MIN_Y = -(GRID_WIDTH - MAP_WIDTH) // 2
PLAYER_SPAWN_GRID_X = PLAYER_SPAWN_GRID_Y = 40.0
GROUND_TILE_WORLD_WIDTH = 1.0
GROUND_DIAMOND_FACE_HEIGHT_PX = 63.0
GROUND_DIAMOND_FACE_WIDTH_PX = 127.0
GROUND_CROP_MIN_X, GROUND_CROP_MIN_Y = 0.0, 0.0
GROUND_CROP_MAX_X, GROUND_CROP_MAX_Y = 127.0, 79.0
GROUND_TILE_LAYOUT_CROP = (64.0, 176.0, 191.0, 255.0)
